version: v2beta1
name: generic-config

pipelines:
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      create_deployments --all     # 3. Deploy Helm charts and manifests specfied as "deployments"
      start_dev app                # 4. Start dev mode "app" (see "dev" section)

dev:
  app:
    labelSelector:
      service: ${SERVICE}
    sync:
      - path: ./src:src
        disableUpload: true
      - path: ./devspace_start.sh
        file: true
    terminal:
      command: ./devspace_start.sh
    ssh:
      enabled: false
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - gitCredentials: true
    ports:
      - port: "9229"
